version: "3.9"
services:
  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: "budget-planner"
      POSTGRES_USER: "local-user"
      POSTGRES_PASSWORD: "local-password"
    ports:
      - "5432:5432"

# docker run --name postgresql -p 5432:5432 -e POSTGRES_USER=local-user -e POSTGRES_PASSWORD=local-password -e POSTGRES_DB=budget-planner -d postgres:16-bookworm