spring.application.name=budget-planner

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:config/liquibase/master-changelog.xml

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/budget-planner
spring.datasource.username=local-user
spring.datasource.password=local-password